'use strict';
// Configuration file reference: the paste-a-.conf checker. CONF_SPEC_INDEX is generated by
// scripts/conf_check/build_conf_index.py; the checker functions run here in a sandbox against
// small pasted samples, so a regression in matching, detection or the finding kinds shows up
// without a browser.

const { test } = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const { readIndexHtml } = require('../lib/parse-index');

const text = readIndexHtml();

function blockFrom(startMarker, endMarker) {
  const start = text.indexOf(startMarker);
  assert.ok(start !== -1, `${startMarker} not found`);
  const end = text.indexOf(endMarker, start);
  assert.ok(end !== -1, `${endMarker} not found after ${startMarker}`);
  return text.slice(start, end);
}

const sandbox = {};
vm.runInNewContext(
  // The Roles page's capability list, reduced to what authorize.conf checks need.
  'function rolesCapabilityIndex() { return { capabilityDescription: new Map([["schedule_search", ""], ["search", ""]]) }; }\n' +
  blockFrom('const CONF_SPEC_INDEX = ', 'function renderConfCheck(') +
  '\nthis.CONF_SPEC_INDEX = CONF_SPEC_INDEX; this.confParseText = confParseText; this.confDetectFile = confDetectFile; this.confCheck = confCheck;',
  sandbox);
const { CONF_SPEC_INDEX, confParseText, confDetectFile, confCheck } = sandbox;

const run = (sample, file) => {
  const entries = confParseText(sample);
  const chosen = file || confDetectFile(entries);
  return { file: chosen, findings: Array.from(confCheck(chosen, entries), f => `${f.line} ${f.kind}${f.suggestions.length ? ` ${f.suggestions.join(',')}` : ''}`) };
};

test('the index covers every article-backed spec file except sourcetypes.conf', () => {
  const files = Object.keys(CONF_SPEC_INDEX);
  assert.equal(files.length, 50);
  assert.ok(!files.includes('sourcetypes.conf'), 'sourcetypes.conf is a machine-written model file');
  for (const file of files) {
    const detail = CONF_SPEC_INDEX[file].d;
    const view = detail.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()) + 'ReferenceView';
    assert.ok(text.includes(`<article id="${view}"`), `${file}: no article ${view}`);
  }
});

test('typos, case, duplicates and comments in inputs.conf', () => {
  const r = run('# comment\n; also a comment\n[monitor:///var/log]\nignoreOlderThn = 7d\nIndex = main\nsourcetype = a\nsourcetype = b\ndisabled = 0\n');
  assert.equal(r.file, 'inputs.conf');
  assert.deepEqual(r.findings, ['4 Unknown setting ignoreOlderThan', '5 Wrong case index', '7 Duplicate']);
});

test('a setting in the wrong stanza names where the spec puts it', () => {
  const r = run('[search]\nmaxresultrows = 50000\n', 'limits.conf');
  assert.deepEqual(r.findings, ['2 Wrong stanza maxresultrows']);
});

test('deprecated settings and stanzas carry the replacement', () => {
  assert.deepEqual(run('[tcpout]\nsslCipher = x\n', 'outputs.conf').findings, ['2 Deprecated sslCipher,cipherSuite']);
  const r = run('[replicationWhitelist]\nfoo = apps/*\n', 'distsearch.conf');
  assert.equal(r.findings.length, 1);
  assert.match(r.findings[0], /^2 Deprecated/);
});

test('authorize.conf grants are checked against known capabilities', () => {
  assert.deepEqual(run('[role_analyst]\nschedule_serach = enabled\nsearch = enabled\nsrchIndexesAllowed = main\n', 'authorize.conf').findings,
    ['2 Unknown capability schedule_search']);
});

test('unknown stanzas suggest the nearest spec stanza', () => {
  const [finding] = confCheck('server.conf', confParseText('[generl]\nserverName = x\n'));
  assert.equal(finding.kind, 'Unknown stanza');
  assert.match(finding.message, /Did you mean \[general\]\?/);
});

test('names Splunk ships in its own defaults are accepted', () => {
  assert.deepEqual(run('[splunktcp]\nconnection_host = ip\n', 'inputs.conf').findings, []);
  assert.deepEqual(run('[role_admin]\nedit_restmap = enabled\n', 'authorize.conf').findings, []);
});

test('pasted text is only read, never stored', () => {
  const block = blockFrom('function renderConfCheck(', 'function confJumpToSetting(');
  assert.doesNotMatch(block, /localStorage|sessionStorage|indexedDB|location\.hash\s*=/);
  assert.match(block, /escapeHtml\(f\.message\)/);
});
